#/bin/bash

kopt="${-}"

set +u
set -e

if [ -z "${LLVM_MINGW_HOME}" ]; then
	LLVM_MINGW_HOME="$(realpath "$(( [ -n "${BASH_SOURCE}" ] && dirname "$(realpath "${BASH_SOURCE[0]}")" ) || dirname "$(realpath "${0}")")""/../../../../..")"
fi

set -u

CROSS_COMPILE_ARCHITECTURE='armv7'
CROSS_COMPILE_TRIPLET="${CROSS_COMPILE_ARCHITECTURE}-w64-mingw32uwp"
CROSS_COMPILE_SYSTEM='windows'
CROSS_COMPILE_SYSROOT="${LLVM_MINGW_HOME}/${CROSS_COMPILE_TRIPLET}"

CC="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-gcc"
CXX="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-g++"
WINDRES="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-windres"
AR="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ar"
AS="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-as"
LD="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ld"
NM="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-nm"
RANLIB="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-ranlib"
STRIP="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-strip"
OBJCOPY="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-objcopy"
READELF="${LLVM_MINGW_HOME}/bin/${CROSS_COMPILE_TRIPLET}-readelf"

export \
	CROSS_COMPILE_TRIPLET \
	CROSS_COMPILE_SYSTEM \
	CROSS_COMPILE_ARCHITECTURE \
	CROSS_COMPILE_SYSROOT \
	CC \
	CXX \
	WINDRES \
	AR \
	AS \
	LD \
	NM \
	RANLIB \
	STRIP \
	OBJCOPY \
	READELF

[[ "${kopt}" = *e*  ]] || set +e
[[ "${kopt}" = *u*  ]] || set +u
